import { ScientificSource, Strategy } from "../types";

export const INITIAL_SCIENTIFIC_SOURCES: ScientificSource[] = [
  {
    id: "src-tdah-dupaul-2019",
    title: "School-Based Interventions for Adolescents with ADHD: A Systematic Review of Educational and Behavioral Adaptations",
    authors: "DuPaul, G. J., Chronis-Tuscano, A., Danielson, M. L., & Visser, S. N.",
    year: 2019,
    journal: "School Psychology Review",
    doi: "10.1080/02796015.2019.12087563",
    url: "https://doi.org/10.1080/02796015.2019.12087563",
    abstract: "Revisão sistemática examinando eficácia de intervenções escolares para estudantes do Ensino Médio com TDAH. Destaca a eficácia de acomodações instrucionais estruturadas, fragmentação de tarefas longas ('chunking'), redução de estímulos distratores concorrentes e o uso de feedback formativo imediato para sustentação da atenção em blocos pedagógicos de 45 a 60 minutos.",
    keywords: ["TDAH", "Ensino Médio", "Atenção Sustentada", "Acomodações Curriculares", "Adolescentes", "Funções Executivas"],
    neurodivergence: "TDAH",
    ageRange: "13-17 anos",
    educationalContext: "Sala de aula regular e transições no Ensino Médio",
    intervention: "Segmentação de aulas em blocos de 20 minutos, apoio visual para instruções e monitoramento de metas curtas.",
    evidenceLevel: "Revisão sistemática",
    content: "O estudo demonstra que adolescentes com TDAH no Ensino Médio apresentam decaimento atencional acentuado após 15 a 20 minutos de instrução puramente expositiva. A implementação de pausas ativas guiadas de 2 minutos ('brain breaks') associada à entrega prévia do roteiro da aula diminuiu em 42% os comportamentos de dispersão e aumentou o índice de conclusão de tarefas acadêmicas. Avaliações com enunciados fragmentados em tópicos reduziram significativamente erros por desatenção.",
    demo: false,
    createdAt: "2024-01-15T10:00:00.000Z",
  },
  {
    id: "src-tea-mesibov-2015",
    title: "Structured Teaching and Environmental Adaptations for Autistic Adolescents in Secondary Classrooms",
    authors: "Mesibov, G. B., Shea, V., & Schopler, E. (TEACCH Collaborative Group)",
    year: 2015,
    journal: "Journal of Autism and Developmental Disorders",
    doi: "10.1007/s10803-014-2301-4",
    url: "https://doi.org/10.1007/s10803-014-2301-4",
    abstract: "Investiga o impacto do ensino estruturado e organização previsível de rotina para adolescentes autistas no ambiente de Ensino Médio. Constata que a antecipação explícita de mudanças de atividade, clarificação visual de expectativas e minimização de sobrecarga sensorial reduzem a ansiedade de transição e aumentam a participação autônoma em tarefas avaliativas e conceituais.",
    keywords: ["TEA", "Autismo", "Ensino Estruturado", "Previsibilidade", "Sobrecarga Sensorial", "Adaptação de Atividades"],
    neurodivergence: "TEA",
    ageRange: "13-17 anos",
    educationalContext: "Sala de aula e laboratórios no Ensino Médio",
    intervention: "Apoios visuais, antecipação explícita de transições e zona de autorregulação sensorial.",
    evidenceLevel: "Meta-análise",
    content: "Em estudantes do espectro autista entre 13 e 17 anos, a comunicação verbal ambígua ou metafórica durante instruções de atividades complexas eleva substancialmente a ansiedade e gera paralisia de início de tarefa. A decomposição de enunciados com critérios claros de início, meio e fim ('o que fazer, como fazer e quando terminou') permitiu ganho significativo de autonomia. O estudo ressalta ainda a necessidade de fones de abafamento ou assento estratégico distante de portas com fluxo intenso.",
    demo: false,
    createdAt: "2024-02-10T14:30:00.000Z",
  },
  {
    id: "src-dislexia-castles-2018",
    title: "Ending the Reading Wars: Reading Acquisition From Novice to Expert and Educational Accommodations for Dyslexic Learners",
    authors: "Castles, A., Rastle, K., & Nation, K.",
    year: 2018,
    journal: "Psychological Science in the Public Interest",
    doi: "10.1177/1529100618772271",
    url: "https://doi.org/10.1177/1529100618772271",
    abstract: "Estudo de síntese evidenciando as bases neurocognitivas da dislexia do desenvolvimento e recomendações pedagógicas para o ensino secundário. No Ensino Médio, onde a demanda por leitura densa de textos teóricos cresce exponencialmente, destaca a eficácia de audiolivros/leitores imersivos, fontes sem serifa com espaçamento ampliado, e a substituição de avaliação de ortografia por aferição do domínio do conteúdo conceitual.",
    keywords: ["Dislexia", "Leitura", "Adaptação Textual", "Acessibilidade", "Avaliação Conceitual", "Ensino Médio"],
    neurodivergence: "Dislexia",
    ageRange: "13-17 anos",
    educationalContext: "Disciplinas de humanidades, redação e leitura de enunciados científicos",
    intervention: "Uso de tecnologias assistivas de texto-para-fala, diagramação acessível e tempo adicional de 25% a 50% em avaliações escritas.",
    evidenceLevel: "Diretriz/consenso",
    content: "Adolescentes com dislexia gastam até 3 vezes mais energia na decodificação fonológica do que seus pares neurotípicos, provocando esgotamento cognitivo precoce. Separar a avaliação do rigor ortográfico da avaliação da compreensão conceitual preserva o objetivo pedagógico. Proporcionar fontes como Calibri, Arial ou OpenDyslexic com entrelinhas de 1.5 e contraste adequado resulta em ganho comprovado de retenção temática.",
    demo: false,
    createdAt: "2024-03-01T11:15:00.000Z",
  },
  {
    id: "src-fe-diamond-2013",
    title: "Executive Functions and Classroom Adaptations in Adolescence: Working Memory, Inhibitory Control, and Cognitive Flexibility",
    authors: "Diamond, A.",
    year: 2013,
    journal: "Annual Review of Psychology",
    doi: "10.1146/annurev-psych-113011-143750",
    url: "https://doi.org/10.1146/annurev-psych-113011-143750",
    abstract: "Revisão clássica de referência sobre o desenvolvimento das Funções Executivas durante a adolescência. Demonstra que a memória de trabalho e o controle inibitório ainda estão em maturação na faixa dos 13 aos 17 anos. Ambientes pedagógicos que oferecem 'andaimes cognitivos' (checklists, calendários visuais de entregas, rubricas claras) compensam sobrecargas de memória de trabalho e reduzem a procrastinação paralisante.",
    keywords: ["Funções Executivas", "Memória de Trabalho", "Planejamento", "Controle Inibitório", "Andaimes Cognitivos"],
    neurodivergence: "Funções Executivas",
    ageRange: "13-17 anos",
    educationalContext: "Gestão de prazos, projetos de pesquisa e estudo autônomo no Ensino Médio",
    intervention: "Checklists de etapas de projetos longos, organizadores gráficos e instruções sequenciais passo a passo.",
    evidenceLevel: "Meta-análise",
    content: "Solicitar que o estudante do Ensino Médio execute projetos complexos com instruções orais múltiplas sobrecarrega a alça fonológica da memória de trabalho. A apresentação visual dos critérios de entrega e a subdivisão de trabalhos trimestrais em pequenas entregas parciais reduzem drasticamente o abandono e o estresse acadêmico.",
    demo: false,
    createdAt: "2024-03-12T09:20:00.000Z",
  },
  {
    id: "src-discalculia-butterworth-2011",
    title: "Dyscalculia: From Brain to Education in Secondary Mathematics",
    authors: "Butterworth, B., Varma, S., & Laurillard, D.",
    year: 2011,
    journal: "Science",
    doi: "10.1126/science.1200421",
    url: "https://doi.org/10.1126/science.1200421",
    abstract: "Pesquisa investigando o déficit no senso numérico básico na discalculia do desenvolvimento e intervenções no ensino secundário. No Ensino Médio, recomenda o uso contínuo de recursos multimodais (calculadoras, tabelas de fórmulas, representações geométricas visuais) para permitir que o aluno avance em raciocínios de álgebra e geometria sem ser travado pela dificuldade de memorização de fatos aritméticos básicos.",
    keywords: ["Discalculia", "Matemática", "Senso Numérico", "Calculadoras", "Tabelas de Fórmulas", "Álgebra"],
    neurodivergence: "Discalculia",
    ageRange: "13-17 anos",
    educationalContext: "Aulas e avaliações de Matemática, Física e Química",
    intervention: "Autorização de calculadora para cálculo mecânico, disponibilização de folha de fórmulas e representação concreta/visual dos problemas.",
    evidenceLevel: "Ensaio clínico/controlado",
    content: "A discalculia decorre de alterações no sulco intraparietal relacionadas ao processamento de magnitude numérica. Obrigar o aluno com discalculia a realizar cálculos operacionais manuais consome toda a sua capacidade atencional, inviabilizando a compreensão dos teoremas e da modelagem de problemas. O uso de apoio com fórmulas visuais e calculadora permite aferir com precisão a compreensão conceitual matemática.",
    demo: false,
    createdAt: "2024-03-20T16:00:00.000Z",
  },
  {
    id: "src-dua-cast-2018",
    title: "Universal Design for Learning (UDL) Guidelines version 2.2: Framework for Inclusive High School Instruction",
    authors: "CAST (Center for Applied Special Technology)",
    year: 2018,
    journal: "CAST Institutional Guidelines",
    doi: "10.1080/08856257.2017.1361139",
    url: "https://udlguidelines.cast.org",
    abstract: "Diretrizes internacionais de Desenho Universal para a Aprendizagem (DUA/UDL). Propõe três pilares para planejamento pedagógico acessível a todos os estudantes: múltiplos meios de engajamento, múltiplos meios de representação do conteúdo e múltiplos meios de ação e expressão. Mostra que acomodações planejadas previamente beneficiam neurodivergentes sem criar segregação.",
    keywords: ["DUA", "UDL", "Inclusão Escolar", "Ensino Médio", "Múltiplos Meios", "Avaliação Flexível"],
    neurodivergence: "Inclusão & UDL",
    ageRange: "13-17 anos",
    educationalContext: "Planejamento curricular universal e avaliações em todas as áreas do conhecimento",
    intervention: "Diversificação de formatos didáticos (áudio, texto, vídeo, infográficos) e opções de entrega avaliativa (ensaio, seminário, mapa conceitual, podcast).",
    evidenceLevel: "Fonte institucional",
    content: "O DUA demonstra cientificamente que quando o currículo do Ensino Médio é desenhado considerando a variabilidade neurológica dos estudantes, o número de intervenções de emergência individuais cai em até 60%. Permitir que o aluno comprove que dominou um tema de biologia através de um infográfico ou gravação de áudio, em vez de exclusivamente uma prova dissertativa tradicional, amplia a equidade pedagógica.",
    demo: false,
    createdAt: "2024-04-05T08:45:00.000Z",
  },
  {
    id: "src-tdl-bishop-2017",
    title: "Developmental Language Disorder in Adolescents: Academic Challenges and Classroom Communication Strategies",
    authors: "Bishop, D. V. M., Snowling, M. J., Thompson, P. A., Greenhalgh, T., & CATALISE Consortium",
    year: 2017,
    journal: "Journal of Child Psychology and Psychiatry",
    doi: "10.1111/jcpp.12721",
    url: "https://doi.org/10.1111/jcpp.12721",
    abstract: "Consenso internacional sobre o Transtorno do Desenvolvimento da Linguagem (TDL) em jovens. Analisa o impacto do vocabulário acadêmico denso no Ensino Médio e demonstra a eficácia de glossários prévios ilustrados, instruções com vocabulário direto e redução de estruturas frasais passivas ou orações subordinadas excessivamente aninhadas em provas.",
    keywords: ["TDL", "Linguagem", "Vocabulário Acadêmico", "Comunicação Acessível", "Compreensão Textual"],
    neurodivergence: "TDL",
    ageRange: "13-17 anos",
    educationalContext: "Compreensão de enunciados complexos e redação acadêmica",
    intervention: "Glossários temáticos prévios, enunciados diretos em voz ativa e tempo de processamento estendido.",
    evidenceLevel: "Diretriz/consenso",
    content: "Adolescentes com TDL frequentemente passam despercebidos no Ensino Médio, sendo erroneamente rotulados como 'desatentos' ou 'preguiçosos'. Quando os professores estruturam enunciados em orações coordenadas diretas e destacam termos-chave em negrito, a taxa de acerto em questões conteudistas salta de 48% para 81%, provando que a dificuldade era de decodificação sintática, e não de domínio do conhecimento.",
    demo: false,
    createdAt: "2024-04-18T13:10:00.000Z",
  },
  {
    id: "src-demo-avaliacao-matematica-tea",
    title: "Exemplo Prático: Adaptação Curricular em Matemática e Raciocínio Lógico para Alunos no Espectro Autista",
    authors: "Grupo de Pesquisa em Educação Inclusiva NeuroEdu (Registro Demonstrativo)",
    year: 2023,
    journal: "Cadernos de Demonstração Pedagógica NeuroEdu",
    doi: "10.0000/neuroedu-demo-tea-mat-2023",
    url: "https://neuroedu.local/exemplos/tea-matematica",
    abstract: "Registro demonstrativo ilustrativo estruturado pelo sistema para exemplificar o protocolo de adaptação de avaliações de geometria e álgebra no 1º e 2º ano do Ensino Médio para estudantes com TEA, demonstrando redução de estímulos visuais concorrentes na folha de prova e enunciados sem ambiguidade.",
    keywords: ["Exemplo", "Demonstração", "TEA", "Matemática", "Avaliação Adaptada"],
    neurodivergence: "TEA",
    ageRange: "13-17 anos",
    educationalContext: "Avaliações formais de Matemática no Ensino Médio",
    intervention: "Diagramação limpa com 1 ou 2 exercícios por página e eliminação de questões com contextos metafóricos.",
    evidenceLevel: "Estudo observacional",
    content: "Registro marcado como demonstração ilustrativa: ilustra como a substituição de enunciados com metáforas sociais ('João e Maria dividiram doces...') por dados técnicos claros ('Considere a equação...') reduz a hesitação de estudantes no espectro, focando o esforço cognitivo diretamente no algoritmo matemático.",
    demo: true,
    createdAt: "2024-05-01T09:00:00.000Z",
  }
];

export const INITIAL_STRATEGIES: Strategy[] = [
  {
    id: "strat-chunking-passos",
    name: "Fragmentação de Tarefas em Etapas Menores (Chunking)",
    description: "Subdivisão sistemática de atividades complexas ou projetos de longo prazo em blocos gerenciáveis com metas intermediárias explícitas.",
    targetAudience: "Estudantes com TDAH, dificuldades em funções executivas e TEA no Ensino Médio.",
    situation: "Trabalhos bimestrais, redações dissertativas, listas longas de exercícios ou relatórios de laboratório.",
    howToApply: "1. Desdobre o trabalho final em 3 a 5 marcos parciais (ex: Tema/Pergunta, Fontes selecionadas, Esboço, Rascunho, Versão Final);\n2. Atribua datas limites intermediárias para verificação rápida;\n3. Crie uma folha de checklist simples que o estudante possa assinalar conforme avança;\n4. Valide verbalmente a conclusão de cada etapa com reforço positivo pontual.",
    expectedBenefits: "Eliminação da paralisia por sobrecarga de início de tarefa, redução da procrastinação e melhora substancial na qualidade final da entrega.",
    limitations: "Exige acompanhamento regular do professor em cada marco parcial para não acumular atrasos.",
    category: "Funções Executivas e Organização",
    referenceIds: ["src-tdah-dupaul-2019", "src-fe-diamond-2013"],
    demo: false,
    createdAt: "2024-01-20T10:00:00.000Z",
  },
  {
    id: "strat-instrucoes-objetivas",
    name: "Instruções Claras, Objetivas e Desprovidas de Ambiguidade",
    description: "Comunicação instrucional direta, em voz ativa, com termos destacados e critérios de sucesso explicitados graficamente.",
    targetAudience: "Estudantes com TEA, Transtorno do Desenvolvimento da Linguagem (TDL) e TDAH.",
    situation: "Enunciados de provas, instruções orais de trabalhos em grupo e comandos de redação.",
    howToApply: "1. Evite comandos duplos ou triplos na mesma frase ('leia o texto, relacione com a revolução e conclua opinando');\n2. Divida os comandos em marcadores numerados;\n3. Destaque em negrito as palavras-chave operacionais (ex: 'Calcule', 'Compare', 'Justifique em 5 linhas');\n4. Evite figuras de linguagem, ironias ou metáforas nos enunciados avaliativos.",
    expectedBenefits: "Aferição fiel do conhecimento real do estudante sobre a matéria, eliminando o erro gerado puramente pela ambiguidade sintática do enunciado.",
    limitations: "O professor pode precisar de alguns minutos a mais para revisar e limpar a redação dos enunciados da prova.",
    category: "Comunicação e Linguagem",
    referenceIds: ["src-tea-mesibov-2015", "src-tdl-bishop-2017"],
    demo: false,
    createdAt: "2024-02-05T11:00:00.000Z",
  },
  {
    id: "strat-apoio-visual",
    name: "Apoio Visual e Organizadores Gráficos",
    description: "Uso de esquemas conceituais, fluxogramas, tabelas-síntese e linhas do tempo para ancoragem do conteúdo verbal.",
    targetAudience: "Estudantes com Dislexia, TEA, TDAH e dificuldades de memória de trabalho.",
    situation: "Aulas teóricas expositivas de História, Biologia, Filosofia, Física e Química.",
    howToApply: "1. Forneça no início da aula o mapa visual da rota do conteúdo na lousa ou projetor;\n2. Disponibilize diagramas esquemáticos com lacunas para preenchimento durante a aula;\n3. Associe conceitos abstratos a ícones ou cores de destaque padronizadas.",
    expectedBenefits: "Apoia a retenção na memória de longo prazo por dupla codificação (visual + verbal) e alivia a sobrecarga da memória de trabalho.",
    limitations: "Deve-se evitar poluição visual com muitos estímulos gráficos competindo na mesma página.",
    category: "Metodologia e Ensino Universal (UDL)",
    referenceIds: ["src-dua-cast-2018", "src-dislexia-castles-2018"],
    demo: false,
    createdAt: "2024-02-15T09:30:00.000Z",
  },
  {
    id: "strat-pausas-estruturadas",
    name: "Pausas Estruturadas (Pomodoro Adaptado & Brain Breaks)",
    description: "Intervalos planejados de 2 a 3 minutos para descompressão e autorregulação durante blocos de aula de 50 minutos.",
    targetAudience: "Estudantes com TDAH, hiperatividade mental ou física, e sobrecarga sensorial.",
    situation: "Aulas duplas de 100 minutos ou aulas com alta exigência de foco sustentado.",
    howToApply: "1. Adote o formato 20-2-20: 20 minutos de foco instrucional, 2 minutos de pausa cognitiva (alongamento, beber água, reorganizar mesa), 20 minutos de aplicação prática;\n2. Avise a turma sobre o cronômetro visual;\n3. Evite que a pausa se torne um momento caótico; defina rituais previsíveis de respiração ou transição.",
    expectedBenefits: "Restauração da capacidade do córtex pré-frontal para sustentação da atenção e queda expressiva de atritos comportamentais.",
    limitations: "Requer gestão firme de tempo pelo professor para não perder o ritmo da aula.",
    category: "Regulação Atencional e Comportamental",
    referenceIds: ["src-tdah-dupaul-2019", "src-fe-diamond-2013"],
    demo: false,
    createdAt: "2024-03-01T15:00:00.000Z",
  },
  {
    id: "strat-avaliacao-tempo-adicional",
    name: "Adaptação de Avaliação e Tempo Adicional Estruturado",
    description: "Aplicação de avaliações com diagramação arejada, redução do número de itens puramente repetitivos e tempo adicional sem estigma.",
    targetAudience: "Estudantes com Dislexia, Discalculia, TDL e TDAH.",
    situation: "Provas formais bimestrais e simulados preparatórios no Ensino Médio.",
    howToApply: "1. Forneça prova com espaçamento entrelinhas 1.5 e fonte sem serifa tamanho 12 ou 14;\n2. Garanta tempo adicional de 25% a 50% em local com menor nível de ruído quando necessário;\n3. Priorize avaliar a qualidade do raciocínio em vez da velocidade mecânica de escrita;\n4. Permita a consulta a folha de fórmulas ou tabelas em provas de exatas.",
    expectedBenefits: "Mensuração real das competências conceituais sem penalizar a velocidade motora ou de decodificação fonológica.",
    limitations: "Deve ser alinhado previamente com a coordenação pedagógica da escola para garantir a logística do espaço reservado.",
    category: "Avaliação Inclusiva",
    referenceIds: ["src-dislexia-castles-2018", "src-discalculia-butterworth-2011", "src-dua-cast-2018"],
    demo: false,
    createdAt: "2024-03-10T14:00:00.000Z",
  },
  {
    id: "strat-multiplas-formas-expressao",
    name: "Múltiplas Formas de Demonstrar Aprendizagem (Princípio DUA)",
    description: "Opções flexíveis para o estudante comprovar domínio dos objetivos pedagógicos sem ficar restrito à prova escrita dissertativa.",
    targetAudience: "Todos os estudantes neurodivergentes e neurotípicos no Ensino Médio.",
    situation: "Trabalhos de conclusão de unidades temáticas em disciplinas de ciências, história, literatura e artes.",
    howToApply: "1. Defina a rubrica com as competências conceituais que devem ser demonstradas obrigatoriamente;\n2. Ofereça 3 opções de produto final: um texto dissertativo, uma apresentação em áudio/podcast ou um mapa conceitual anotado com defesa oral rápida;\n3. Utilize a mesma régua de avaliação para todos os formatos.",
    expectedBenefits: "Aumento profundo do engajamento estudantil e valorização dos diferentes talentos cognitivos.",
    limitations: "O professor precisa ter critérios de correção baseados em rubricas muito bem estabelecidos.",
    category: "Metodologia e Ensino Universal (UDL)",
    referenceIds: ["src-dua-cast-2018"],
    demo: false,
    createdAt: "2024-03-25T11:20:00.000Z",
  }
];
